services:
  server:
    image: ubuntu:22.04
    volumes:
      - ./bins:/app
    expose:
      - 60011
    working_dir: /app/caches
    command: bash -c "/app/server"

  client:
    image: ubuntu:22.04
    volumes:
      - ./bins:/app
    expose:
      - 60011
    # tty: true
    working_dir: /app
    command: bash -c "./client MapleMono-NF-unhinted.zip"